export const GET_LIST_PROVINCE = "GET_LIST_PROVINCE";
export const SET_PROVINCE_CODE = "SET_PROVINCE_CODE";
export const GET_LIST_DISTRICT = "GET_LIST_DISTRICT";
export const SET_DISTRICT_CODE = "SET_DISTRICT_CODE";
export const GET_LIST_WARD = "GET_LIST_WARD";